@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}

### Pools - Create
POST http://{{host}}/pools
content-type: application/json

{
    "title": "Bolão do Mhayk"
}

### Pools - Count
GET http://{{host}}/pools/count

### Users - Count
GET http://{{host}}/users/count

### Guesses - Count
GET http://{{host}}/guesses/count
