@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}

### Pools - Create without owner
POST http://{{host}}/polls
content-type: application/json

{
    "title": "Bolão do Mhayk"
}

### Pools - Create with owner
POST http://{{host}}/polls
Authorization: Bearer ...
content-type: application/json

{
    "title": "Bolão com dono!"
}

### Pools - Count
GET http://{{host}}/polls/count

### Users - Count
GET http://{{host}}/users/count

### Users - Auth - me
GET http://{{host}}/me
Authorization: Bearer ...

### Users - Auth
POST http://{{host}}/users
content-type: application/json

{
    "access_token": "..."
}


### Guesses - Count
GET http://{{host}}/guesses/count


