@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@jwt_token = ...

### Polls - Create without owner
POST http://{{host}}/polls
content-type: application/json

{
    "title": "Bolão do Mhayk"
}

### Polls - Create with owner
POST http://{{host}}/polls
Authorization: Bearer {{jwt_token}}
content-type: application/json

{
    "title": "Bolão com dono!"
}

### Polls - Count
GET http://{{host}}/polls/count

### Pools - List polls
GET http://{{host}}/polls
Authorization: Bearer {{jwt_token}}

### Pools - get a poll
GET http://{{host}}/polls/G2GHFI
Authorization: Bearer {{jwt_token}}

### Pools - create guess
POST http://{{host}}/polls/clackfq3n0001fxymblhss8g3/games/cla2p6wgc0007fxugodx39k9q/guesses
Authorization: Bearer {{jwt_token}}
content-type: application/json

{
    "firstTeamPoints": 2,
    "secondTeamPoints": 5
}

### Users - Count
GET http://{{host}}/users/count

### Users - Auth - me
GET http://{{host}}/me
Authorization: Bearer {{jwt_token}}

### Users - Auth
POST http://{{host}}/users
content-type: application/json

{
    "access_token": "..."
}


### Guesses - Count
GET http://{{host}}/guesses/count

### Games - List games in a poll
GET http://{{host}}/polls/clackfq3n0001fxymblhss8g3/games
Authorization: Bearer {{jwt_token}}